### ISSUE TITLE
Error when running the scanner with RaspberryPi

### ISSUE THREAD

**Issue by SohamJani** [jacopo-j/mcr12_serial#1]
I get the following error "super() takes at least 1 argument. 0 given", on line 25 of mcr12_serail.py file, when running "bcd = BarcodeScanner("/path/to/serial/device", baudrate=9600)" 

I'm using Rpi 3 with the USB module. Can the problem be at the path given in the above command? 

Thanks for the library

**Comment by jacopo-j** [comment]
Please use Python 3 instead of Python 2, I think that is the problem.

**Comment by SohamJani** [comment]
Thanks for the prompt response. On using the python 3, I get the error "No such file or directory" for "/path/to/serial/device".  Would you know how to refer to the USB directory on the Linux Jesse for Pi3?

**Comment by jacopo-j** [comment]
You need to determine the serial port corresponding to your scanner and replace `/path/to/serial/device` with that (for example `/dev/ttyS1`). Make sure you have set the scanner in serial mode (see the manual) beforehand.

**Comment by SohamJani** [comment]
I can set it to serial mode, but does that mean that I now have to switch to RS232 connector from the USB port?

**Comment by jacopo-j** [comment]
I don't know as that differs between models, you should refer to the manual or contact the vendor for that.
